---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: fedora-kinoite-nitro-an515-43
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: 43 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: dnf
    repos:
      copr:
        - "@kdesig/kde-beta"
    install:
      packages:
        - plasma-firewall
        - libreoffice-calc
        - libreoffice-core
        - libreoffice-data
        - libreoffice-emailmerge
        - libreoffice-graphicfilter
        - libreoffice-help-pt-BR
        - libreoffice-impress
        - libreoffice-kf6
        - libreoffice-langpack-pt-BR
        - libreoffice-ogltrans
        - libreoffice-opensymbol-fonts
        - libreoffice-pdfimport
        - libreoffice-pyuno
        - libreoffice-ure
        - libreoffice-ure-common
        - libreoffice-writer
        - plasma-login-manager
        - kcm-plasmalogin
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - firewall-config
        - kdebugsettings
        - plasma-drkonqi
        - sddm
        - sddm-kcm
        - sddm-wayland-plasma
        - tuned
        - tuned-ppd

  - type: brew

  - type: fonts
    fonts:
      nerd-fonts:
        - NerdFontsSymbolsOnly
      google-fonts:
        - Fira Sans
        - Fira Mono

  - type: default-flatpaks
    notify: false # Do not send notification on first boot
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: Flathub
      # install: [org.mozilla.firefox] # Example: Install specific flatpaks here if desired

  - type: script
    scripts:
      - remove-flatpaks.sh
      - setup-repos.sh
      - setup-tlp.sh
      - configure-nvidia.sh

  - type: dnf
    install:
      packages:
        - libva-nvidia-driver # From RPM Fusion (setup-repos.sh)
        - tlp # From TLP Repo (setup-tlp.sh)
        - tlp-pd
        - tlp-rdw

  - type: systemd
    system:
      enabled:
        - plasmalogin.service
        - tlp.service
        - tlp-pd.service
      masked:
        - systemd-rfkill.service
        - systemd-rfkill.socket

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
