---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: fedora-kinoite-nitro-an515-43
description: Custom Fedora Kinoite (CachyOS Kernel / Nvidia Open) optimized for the Acer Nitro 5 (AN515-43).

base-image: ghcr.io/ublue-os/kinoite-main
image-version: 43

modules:
  - type: rpm-ostree
    install:
      # RPM Fusion (Fedora 43 - Match image-version)
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-43.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-43.noarch.rpm
  - type: dnf
    repos:
      copr:
        - "@kdesig/kde-beta"
        - "bieszczaders/kernel-cachyos"
        - "bieszczaders/kernel-cachyos-addons"
    install:
      packages:
        # CachyOS Kernel (Requires Nvidia Driver Installation)
        - kernel-cachyos
        - kernel-cachyos-modules
        - kernel-cachyos-modules-extra
        - kernel-cachyos-devel-matched
        # Nvidia Userspace (RPM Fusion)
        - akmod-nvidia
        - nvidia-driver
        - nvidia-settings
        - nvidia-driver-cuda
        - nvidia-driver-cuda-libs
        # CachyOS Addons
        - cachyos-settings
        - cachyos-ksm-settings
        - scx-scheds
        - scx-manager
        - scx-tools
        - uksmd
        # KDE Plasma
        - plasma-firewall
        - plasma-login-manager
        - kcm-plasmalogin
        - plasma-discover-rpm-ostree
        # LibreOffice
        - libreoffice-writer
        - libreoffice-calc
        - libreoffice-impress
        - libreoffice-draw
        - libreoffice-math
        - libreoffice-graphicfilter
        - libreoffice-kf6
        - libreoffice-langpack-pt-BR
        # Container Management
        - distrobox
    remove:
      packages:
        # ZRAM (replaced by cachyos-settings)
        - zram-generator-defaults
        # Browser
        - firefox
        - firefox-langpacks
        # Login Manager (replaced by Plasma Login)
        - sddm
        - sddm-kcm
        - sddm-wayland-plasma
        # Debug Tools
        - kdebugsettings
        - plasma-drkonqi
        - firewall-config
        # Kernel Replacement (Stock Fedora)
        - kernel
        - kernel-core
        - kernel-modules
        - kernel-modules-core
        - kernel-modules-extra
        # Power Management (replaced by TLP)
        - tuned
        - tuned-ppd
        - power-profiles-daemon
        # Input Method: fcitx5 (core)
        - fcitx5
        - fcitx5-autostart
        - fcitx5-configtool
        - fcitx5-data
        - fcitx5-libs
        - fcitx5-lua
        - kcm-fcitx5
        # Input Method: fcitx5 (GTK/Qt)
        - fcitx5-gtk
        - fcitx5-gtk3
        - fcitx5-gtk4
        - fcitx5-qt
        - fcitx5-qt5
        - fcitx5-qt6
        - fcitx5-qt-libfcitx5qtdbus
        - fcitx5-qt-libfcitx5qt6widgets
        - fcitx5-qt-qt6gui
        # Input Method: fcitx5 (language engines)
        - fcitx5-chewing
        - fcitx5-chinese-addons
        - fcitx5-chinese-addons-data
        - fcitx5-hangul
        - fcitx5-libthai
        - fcitx5-m17n
        - fcitx5-mozc
        - fcitx5-sayura
        - fcitx5-unikey
        # Container Management (replaced by distrobox)
        - toolbox
        # System Monitors
        - htop
        - nvtop
        # Text Editor (kwrite is already included)
        - kate
        - kate-libs
        - kate-plugins
        - kate-krunner-plugin
        # Input Method: ibus engines (unused languages)
        - ibus-anthy
        - ibus-anthy-python
        - ibus-hangul
        - ibus-libpinyin
        - ibus-chewing
        - ibus-m17n
        - kasumi-unicode
        # Firefox residual
        - mozilla-filesystem

  - type: brew

  - type: fonts
    fonts:
      nerd-fonts:
        - NerdFontsSymbolsOnly
      google-fonts:
        - Fira Sans
        - Fira Mono

  - type: script
    scripts:
      - upgrade-kde-beta.sh
      - setup-tlp.sh
      - install-epson-escpr.sh
      - install-chrome.sh
      - install-oh-my-bash.sh
      - setup-root-theme-sync.sh
      - configure-grub.sh
      - configure-nvidia.sh
      - fix-selinux-cachyos.sh
      - set-cachyos-default.sh

  - type: dnf
    install:
      packages:
        - tlp
        - tlp-pd
        - tlp-rdw

  - type: default-flatpaks
    configurations:
      - scope: system
        notify: true
        repo:
          url: https://dl.flathub.org/repo/flathub.flatpakrepo
          name: flathub
          title: Flathub
        install:
          - org.kde.okular
          - org.kde.elisa
          - org.kde.haruna
          - org.kde.skanpage
          - org.kde.kalk
          - org.kde.koko
          - org.kde.marknote
          - io.github.DenysMb.Kontainer
          - org.kde.merkuro
      - scope: user
        repo:
          url: https://dl.flathub.org/repo/flathub.flatpakrepo
          name: flathub
        remove-repo: true

  - type: systemd
    system:
      enabled:
        - plasmalogin.service
        - tlp.service
        - tlp-pd.service
        - rpm-ostreed-automatic.timer
      masked:
        - systemd-rfkill.service
        - systemd-rfkill.socket

  - type: signing
