---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: fedora-kinoite-nitro-an515-43
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: 43

modules:
  - type: dnf
    repos:
      copr:
        - "@kdesig/kde-beta"
    install:
      packages:
        - plasma-firewall
        - libreoffice-base
        - libreoffice-calc
        - libreoffice-draw
        - libreoffice-emailmerge
        - libreoffice-graphicfilter
        - libreoffice-help-pt-BR
        - libreoffice-impress
        - libreoffice-kf6
        - libreoffice-langpack-pt-BR
        - libreoffice-math
        - libreoffice-pyuno
        - libreoffice-writer
        - plasma-login-manager
        - kcm-plasmalogin
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - firewall-config
        - kdebugsettings
        - plasma-drkonqi
        - sddm
        - sddm-kcm
        - sddm-wayland-plasma
        - tuned
        - tuned-ppd

  - type: brew

  - type: fonts
    fonts:
      nerd-fonts:
        - NerdFontsSymbolsOnly
      google-fonts:
        - Fira Sans
        - Fira Mono

  - type: script
    scripts:
      - remove-flatpaks.sh
      - setup-repos.sh
      - setup-tlp.sh
      - configure-nvidia.sh

  - type: dnf
    install:
      packages:
        - libva-nvidia-driver # From RPM Fusion (setup-repos.sh)
        - tlp
        - tlp-pd
        - tlp-rdw

  - type: default-flatpaks
    configurations:
      - repo:
          url: https://dl.flathub.org/repo/flathub.flatpakrepo
          name: flathub
          title: Flathub
        install:
          - com.google.Chrome
          - org.kde.okular
          - org.kde.elisa
          - org.kde.haruna
          - org.kde.skanpage
          - org.kde.kalk
          - org.kde.koko
          - org.kde.marknote

  - type: systemd
    system:
      enabled:
        - plasmalogin.service
        - tlp.service
        - tlp-pd.service
      masked:
        - systemd-rfkill.service
        - systemd-rfkill.socket

  - type: signing
