---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: fedora-kinoite-nitro-an515-43
description: Custom Fedora Kinoite (Fedora 43 / KDE Plasma Master / Nvidia) optimized for the Acer Nitro 5 (AN515-43). Bleeding Edge Edition.

base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: 43

modules:
  - type: dnf
    repos:
      copr:
        - "@kdesig/kde-beta"
        - jhyub/supergfxctl-plasmoid
        - lukenukem/asus-linux
    install:
      packages:
        # Container Management
        - distrobox
        # Hybrid Graphics
        - supergfxctl
        - supergfxctl-plasmoid
        # KDE Plasma
        - kcm-plasmalogin
        - plasma-discover-rpm-ostree
        - plasma-firewall
        - plasma-login-manager
        # LibreOffice
        - libreoffice-calc
        - libreoffice-draw
        - libreoffice-graphicfilter
        - libreoffice-impress
        - libreoffice-kf6
        - libreoffice-langpack-pt-BR
        - libreoffice-math
        - libreoffice-writer
        # Power Management
        - tlp
        - tlp-pd
        - tlp-rdw
    remove:
      packages:
        # Browser (replaced by Chrome)
        - firefox
        - firefox-langpacks
        - mozilla-filesystem
        # Container Management (replaced by distrobox)
        - toolbox
        # Debug & System Tools
        - firewall-config
        - kdebugsettings
        - plasma-drkonqi
        # Input Method: fcitx5 (core & engines)
        - fcitx5
        - fcitx5-autostart
        - fcitx5-chewing
        - fcitx5-chinese-addons
        - fcitx5-chinese-addons-data
        - fcitx5-configtool
        - fcitx5-data
        - fcitx5-gtk
        - fcitx5-gtk3
        - fcitx5-gtk4
        - fcitx5-hangul
        - fcitx5-libs
        - fcitx5-libthai
        - fcitx5-lua
        - fcitx5-m17n
        - fcitx5-mozc
        - fcitx5-qt
        - fcitx5-qt-libfcitx5qt6widgets
        - fcitx5-qt-libfcitx5qtdbus
        - fcitx5-qt-qt6gui
        - fcitx5-qt5
        - fcitx5-qt6
        - fcitx5-sayura
        - fcitx5-unikey
        - kcm-fcitx5
        - libchewing
        - libime
        - libime-data
        # Input Method: ibus (engines)
        - ibus-anthy
        - ibus-anthy-python
        - ibus-chewing
        - ibus-hangul
        - ibus-libpinyin
        - ibus-m17n
        - kasumi-common
        - kasumi-unicode
        # Login Manager (replaced by Plasma Login)
        - sddm
        - sddm-breeze
        - sddm-kcm
        - sddm-wayland-plasma
        # Power Management (replaced by TLP)
        - tuned
        - tuned-ppd
        # System Monitors
        - htop
        - nvtop
        # Text Editor (KWrite is already included)
        - kate
        - kate-krunner-plugin
        - kate-libs
        - kate-plugins

  - type: brew

  - type: fonts
    fonts:
      nerd-fonts:
        - NerdFontsSymbolsOnly
      google-fonts:
        - Fira Sans
        - Fira Mono

  - type: files
    files:
      - source: rpms
        destination: /tmp/rpms

  - type: script
    scripts:
      - upgrade-kde-beta.sh
      - setup-tlp.sh
      - install-epson-escpr.sh
      - install-chrome.sh
      - install-oh-my-bash.sh
      - setup-root-theme-sync.sh
      - configure-grub.sh
      - configure-nvidia.sh

  - type: default-flatpaks
    configurations:
      - scope: system
        notify: true
        repo:
          url: https://dl.flathub.org/repo/flathub.flatpakrepo
          name: flathub
          title: Flathub
        install:
          - org.kde.okular
          - org.kde.elisa
          - org.kde.haruna
          - org.kde.skanpage
          - org.kde.kalk
          - org.kde.koko
          - org.kde.marknote
          - io.github.DenysMb.Kontainer
          - org.kde.merkuro
      - scope: user
        repo:
          url: https://dl.flathub.org/repo/flathub.flatpakrepo
          name: flathub
        remove-repo: true

  - type: systemd
    system:
      enabled:
        - nvidia-powerd.service
        - plasmalogin.service
        - rpm-ostreed-automatic.timer
        - supergfxd.service
        - tlp.service
        - tlp-pd.service
      masked:
        - systemd-rfkill.service
        - systemd-rfkill.socket

  - type: signing
